package demo.ssm.mapper;

import demo.ssm.pojo.SC;
import demo.ssm.pojo.SCExample;
import demo.ssm.pojo.SCKey;
import java.util.List;

import demo.ssm.pojo.schedule;
import org.apache.ibatis.annotations.Param;

public interface SCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int countByExample(SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int deleteByExample(SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int deleteByPrimaryKey(SCKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int insert(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int insertSelective(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    List<SC> selectByExample(SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    SC selectByPrimaryKey(SCKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") SC record, @Param("example") SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByExample(@Param("record") SC record, @Param("example") SCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByPrimaryKeySelective(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByPrimaryKey(SC record);

    List<schedule> myshedule(@Param("sNo") String sNo);
}