package demo.ssm.mapper;

import demo.ssm.pojo.TC;
import demo.ssm.pojo.TCExample;
import demo.ssm.pojo.TCKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int countByExample(TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int deleteByExample(TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int deleteByPrimaryKey(TCKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int insert(TC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int insertSelective(TC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    List<TC> selectByExample(TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    TC selectByPrimaryKey(TCKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByExampleSelective(@Param("record") TC record, @Param("example") TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByExample(@Param("record") TC record, @Param("example") TCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByPrimaryKeySelective(TC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tc
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    int updateByPrimaryKey(TC record);
}