package demo.ssm.pojo;

public class Course {
    @Override
    public String toString() {
        return "Course{" +
                "cNo='" + cNo + '\'' +
                ", cName='" + cName + '\'' +
                ", cPno='" + cPno + '\'' +
                ", cCredit=" + cCredit +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_pno
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String cPno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.c_credit
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private Integer cCredit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_no
     *
     * @return the value of course.c_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_no
     *
     * @param cNo the value for course.c_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setcNo(String cNo) {
        this.cNo = cNo == null ? null : cNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_name
     *
     * @return the value of course.c_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_name
     *
     * @param cName the value for course.c_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_pno
     *
     * @return the value of course.c_pno
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getcPno() {
        return cPno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_pno
     *
     * @param cPno the value for course.c_pno
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setcPno(String cPno) {
        this.cPno = cPno == null ? null : cPno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.c_credit
     *
     * @return the value of course.c_credit
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public Integer getcCredit() {
        return cCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.c_credit
     *
     * @param cCredit the value for course.c_credit
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setcCredit(Integer cCredit) {
        this.cCredit = cCredit;
    }
}