package demo.ssm.pojo;

public class SC extends SCKey {
    @Override
    public String toString() {
        return "SC{" +
                "sNo="+getsNo()+
                ",cId="+getcId()+
                ",grade=" + grade +
                ", scStatus='" + scStatus + '\'' +
                ", info='" + info + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.grade
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.sc_status
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String scStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sc.info
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.grade
     *
     * @return the value of sc.grade
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.grade
     *
     * @param grade the value for sc.grade
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.sc_status
     *
     * @return the value of sc.sc_status
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getScStatus() {
        return scStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.sc_status
     *
     * @param scStatus the value for sc.sc_status
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setScStatus(String scStatus) {
        this.scStatus = scStatus == null ? null : scStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sc.info
     *
     * @return the value of sc.info
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sc.info
     *
     * @param info the value for sc.info
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}