package demo.ssm.pojo;

public class Student {
    @Override
    public String toString() {
        return "Student{" +
                "sNo='" + sNo + '\'' +
                ", sName='" + sName + '\'' +
                ", sAge=" + sAge +
                ", sSex='" + sSex + '\'' +
                ", sDept='" + sDept + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String sNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_age
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private Integer sAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_sex
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String sSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.s_dept
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String sDept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_no
     *
     * @return the value of student.s_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getsNo() {
        return sNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_no
     *
     * @param sNo the value for student.s_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setsNo(String sNo) {
        this.sNo = sNo == null ? null : sNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param sName the value for student.s_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_age
     *
     * @return the value of student.s_age
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public Integer getsAge() {
        return sAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_age
     *
     * @param sAge the value for student.s_age
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setsAge(Integer sAge) {
        this.sAge = sAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_sex
     *
     * @return the value of student.s_sex
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getsSex() {
        return sSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_sex
     *
     * @param sSex the value for student.s_sex
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setsSex(String sSex) {
        this.sSex = sSex == null ? null : sSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_dept
     *
     * @return the value of student.s_dept
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getsDept() {
        return sDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_dept
     *
     * @param sDept the value for student.s_dept
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setsDept(String sDept) {
        this.sDept = sDept == null ? null : sDept.trim();
    }
}