package demo.ssm.pojo;

public class TC extends TCKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.c_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.time
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tc.tc_status
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String tcStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.c_no
     *
     * @return the value of tc.c_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.c_no
     *
     * @param cNo the value for tc.c_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setcNo(String cNo) {
        this.cNo = cNo == null ? null : cNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.time
     *
     * @return the value of tc.time
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.time
     *
     * @param time the value for tc.time
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tc.tc_status
     *
     * @return the value of tc.tc_status
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getTcStatus() {
        return tcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tc.tc_status
     *
     * @param tcStatus the value for tc.tc_status
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setTcStatus(String tcStatus) {
        this.tcStatus = tcStatus == null ? null : tcStatus.trim();
    }
}