package demo.ssm.pojo;

public class Teacher {
    @Override
    public String toString() {
        return "Teacher{" +
                "tNo='" + tNo + '\'' +
                ", tName='" + tName + '\'' +
                ", tAge=" + tAge +
                ", tSex='" + tSex + '\'' +
                ", tTel='" + tTel + '\'' +
                ", tDept='" + tDept + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String tNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String tName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_age
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private Integer tAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_sex
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String tSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_tel
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String tTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.t_dept
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String tDept;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_no
     *
     * @return the value of teacher.t_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String gettNo() {
        return tNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_no
     *
     * @param tNo the value for teacher.t_no
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void settNo(String tNo) {
        this.tNo = tNo == null ? null : tNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_name
     *
     * @return the value of teacher.t_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_name
     *
     * @param tName the value for teacher.t_name
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void settName(String tName) {
        this.tName = tName == null ? null : tName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_age
     *
     * @return the value of teacher.t_age
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public Integer gettAge() {
        return tAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_age
     *
     * @param tAge the value for teacher.t_age
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void settAge(Integer tAge) {
        this.tAge = tAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_sex
     *
     * @return the value of teacher.t_sex
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String gettSex() {
        return tSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_sex
     *
     * @param tSex the value for teacher.t_sex
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void settSex(String tSex) {
        this.tSex = tSex == null ? null : tSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_tel
     *
     * @return the value of teacher.t_tel
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String gettTel() {
        return tTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_tel
     *
     * @param tTel the value for teacher.t_tel
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void settTel(String tTel) {
        this.tTel = tTel == null ? null : tTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_dept
     *
     * @return the value of teacher.t_dept
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String gettDept() {
        return tDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_dept
     *
     * @param tDept the value for teacher.t_dept
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void settDept(String tDept) {
        this.tDept = tDept == null ? null : tDept.trim();
    }
}