package demo.ssm.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String uPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_flag
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    private String uFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_flag
     *
     * @return the value of user.u_flag
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public String getuFlag() {
        return uFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_flag
     *
     * @param uFlag the value for user.u_flag
     *
     * @mbggenerated Sat Nov 26 00:22:11 CST 2022
     */
    public void setuFlag(String uFlag) {
        this.uFlag = uFlag == null ? null : uFlag.trim();
    }
}